export const BattlemechsSeed = [
  {
    type: 'Commando',
    subtype: 'COM-1B',    
    class: 'light',
    stock_role: 'Light Sniper & Scout',
    tonnageTotal: 25,
    tonnageFree: 7,
    damageMelee: 7,
    damageDFA: 50,
    walkDistance: 210,
    jumpJets: 8,
    cost: 2000000,
    rarity: 0
  },
  {
    type: 'Commando',
    subtype: 'COM-2D',
    class: 'light',
    stock_role: 'Light Striker & Scout',
    tonnageTotal: 25,
    tonnageFree: 7,
    damageMelee: 7,
    damageDFA: 50,
    walkDistance: 210,
    jumpJets: 8,
    cost: 2000000,
    rarity: 0
  },
  {
    type: 'Locust',
    subtype: 'LCT-1M',
    class: 'light',
    stock_role: 'Extremely Fast Scout',
    tonnageTotal: 25,
    tonnageFree: 7,
    damageMelee: 7,
    damageDFA: 50,
    walkDistance: 210,
    jumpJets: 8,
    cost: 1642000,
    rarity: 0
  },
  {
    type: 'Locust',
    subtype: 'LCT-1S',
    class: 'light',
    stock_role: 'Extremely Fast Scout',
    tonnageTotal: 25,
    tonnageFree: 7,
    damageMelee: 7,
    damageDFA: 50,
    walkDistance: 210,
    jumpJets: 8,
    cost: 1800000,
    rarity: 0
  },  
];
